 "use client";
import {useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {Button,Input} from "@/components/ui";
import {Heart,LogOut,Plus,ShieldCheck,UserRound,XCircle} from "lucide-react";
export default function DashboardClient({user,profile,memberships}:{user:{id:string;email:string};profile:{username:string;display_name:string|null}|null;memberships:any[]}){
 const supabase=createClient();const [partner,setPartner]=useState("");const [notice,setNotice]=useState("");const [error,setError]=useState("");
 async function createContract(){setNotice("");setError("");const {data,error}=await supabase.rpc("create_contract",{partner_username:partner.trim().toLowerCase()});if(error)setError(error.message);else{setNotice(`契约创建成功：${data}`);setPartner("");}}
 async function logout(){await supabase.auth.signOut();window.location.href="/";}
 return <main className="min-h-screen bg-slate-50"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><a href="/" className="flex items-center gap-2 font-black"><span className="grid h-9 w-9 place-items-center rounded-xl bg-rose-500 text-white"><Heart size={18} fill="currentColor"/></span>Love Pact</a><Button variant="ghost" onClick={logout}><LogOut size={16} className="mr-2"/>退出</Button></div></header>
 <div className="mx-auto max-w-6xl px-5 py-10"><div className="grid gap-6 md:grid-cols-[1fr_320px]"><section>
  <div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><p className="text-sm font-semibold text-rose-500">MY SPACE</p><h1 className="mt-2 text-3xl font-black">你好，{profile?.display_name||profile?.username||"朋友"}。</h1><p className="mt-2 text-sm text-slate-500">{user.email}</p></div>
  <div className="mt-6 rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><div className="flex items-center gap-2"><Heart size={19} className="text-rose-500" fill="currentColor"/><h2 className="font-black">建立新的恋爱契约</h2></div><p className="mt-2 text-sm leading-6 text-slate-500">输入对方已经注册的用户名。</p><div className="mt-5 flex gap-3"><Input value={partner} onChange={e=>setPartner(e.target.value)} placeholder="对方用户名，例如 mia_01"/><Button onClick={createContract} disabled={!partner.trim()}><Plus size={16} className="mr-2"/>创建</Button></div>{notice&&<p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-600">{error}</p>}</div>
  <div className="mt-6 space-y-4">{memberships.length===0?<div className="rounded-3xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">还没有契约。先邀请另一半吧 ❤️</div>:memberships.map(m=>{const c=Array.isArray(m.contracts)?m.contracts[0]:m.contracts;return <div key={m.contract_id} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-slate-400">CONTRACT</p><h3 className="mt-1 text-xl font-black">{c?.contract_code}</h3></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-600">{c?.status}</span></div><p className="mt-4 text-sm text-slate-500">你的角色：{m.role==="creator"?"发起人":"另一半"}</p>{c?.status==="active"&&<Dissolution contractId={c.id}/>}</div>})}</div>
 </section>
 <aside className="space-y-4"><div className="rounded-3xl border border-slate-200 bg-white p-6"><UserRound size={20}/><p className="mt-4 text-xs font-bold text-slate-400">USERNAME</p><p className="mt-1 font-black">{profile?.username}</p></div><div className="rounded-3xl border border-slate-200 bg-white p-6"><ShieldCheck className="text-emerald-500" size={20}/><h3 className="mt-4 font-black">安全提示</h3><p className="mt-2 text-sm leading-6 text-slate-500">一方不能单方面结束契约，解约需要另一方确认。</p></div></aside>
 </div></div></main>
}
function Dissolution({contractId}:{contractId:string}){const supabase=createClient();const[open,setOpen]=useState(false);const[reason,setReason]=useState("");const[msg,setMsg]=useState("");
 async function request(){const {error}=await supabase.rpc("request_dissolution",{target_contract:contractId,request_reason:reason||null});setMsg(error?error.message:"解约申请已发送，等待另一方确认。");if(!error)setOpen(false);}
 return <div className="mt-5 border-t border-slate-100 pt-5">{!open?<button onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-red-600"><XCircle size={16}/>申请解约</button>:<div className="space-y-3"><Input value={reason} onChange={e=>setReason(e.target.value)} placeholder="可选：告诉对方你的原因"/><div className="flex gap-2"><Button variant="outline" onClick={()=>setOpen(false)}>取消</Button><Button onClick={request}>发送解约申请</Button></div></div>}{msg&&<p className="mt-3 text-sm text-slate-500">{msg}</p>}</div>}